# Generated by Django 5.0.6 on 2025-09-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_deleted_at_user_is_disabled_user_is_locked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockoutPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50)),
                ('threshold1', models.IntegerField(default=3)),
                ('wait1', models.IntegerField(default=60)),
                ('threshold2', models.IntegerField(default=5)),
                ('wait2', models.IntegerField(default=300)),
                ('threshold3', models.IntegerField(default=10)),
                ('wait3', models.IntegerField(default=1800)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
