# Generated by Django 5.0.6 on 2025-09-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_lockoutpolicy_user_failed_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockoutpolicy',
            name='name',
            field=models.CharField(default='default', max_length=64),
        ),
        migrations.AlterField(
            model_name='lockoutpolicy',
            name='threshold3',
            field=models.IntegerField(default=8),
        ),
    ]
