# Generated by Django 5.0.6 on 2025-09-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_delete_requested_at_user_is_suspended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_reauth_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
