# Generated by Django 5.0.6 on 2025-10-05 00:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_authrequestlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authrequestlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='authrequestlog',
            name='action',
            field=models.CharField(choices=[('magic_link', 'Magic Link'), ('email_otp', 'Email OTP'), ('sms_otp', 'SMS OTP'), ('totp', 'TOTP Verification'), ('backup_code', 'Backup Code Use'), ('webauthn', 'WebAuthn/Passkey'), ('login_attempt', 'Login Attempt'), ('password_reset', 'Password Reset'), ('unknown', 'Unknown')], default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='authrequestlog',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='authrequestlog',
            name='success',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='authrequestlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authrequestlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='authrequestlog',
            index=models.Index(fields=['action'], name='accounts_au_action_8364b0_idx'),
        ),
        migrations.AddIndex(
            model_name='authrequestlog',
            index=models.Index(fields=['created_at'], name='accounts_au_created_a54e86_idx'),
        ),
        migrations.AddIndex(
            model_name='authrequestlog',
            index=models.Index(fields=['ip'], name='accounts_au_ip_b179e1_idx'),
        ),
        migrations.AddIndex(
            model_name='authrequestlog',
            index=models.Index(fields=['email'], name='accounts_au_email_bdc8d2_idx'),
        ),
    ]
