# Generated by Django 5.0.6 on 2025-10-06 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_authrequestlog_options_authrequestlog_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('global', 'Global (Admin Default)'), ('user', 'User Specific')], default='user', max_length=16)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('login_policy', models.JSONField(default=dict)),
                ('profile_edit_policy', models.JSONField(default=dict)),
                ('delete_account_policy', models.JSONField(default=dict)),
                ('sensitive_ops_policy', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_policies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
