# Generated by Django 5.0.6 on 2025-10-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_authpolicy'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='authpolicy',
            constraint=models.UniqueConstraint(fields=('user', 'scope'), name='unique_user_auth_policy'),
        ),
    ]
