# Generated by Django 5.0.6 on 2025-10-06 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_authpolicy_unique_user_auth_policy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authpolicy',
            old_name='delete_account_policy',
            new_name='applicable_methods',
        ),
        migrations.RenameField(
            model_name='authpolicy',
            old_name='login_policy',
            new_name='selected_methods',
        ),
        migrations.RemoveField(
            model_name='authpolicy',
            name='profile_edit_policy',
        ),
        migrations.RemoveField(
            model_name='authpolicy',
            name='sensitive_ops_policy',
        ),
    ]
