# Generated by Django 5.0.6 on 2025-10-06 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_delete_account_policy_authpolicy_applicable_methods_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase_hash', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_phrase_policy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
