# Generated by Django 5.2.7 on 2025-10-18 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=280, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("basketball", "Basketball"),
                            ("soccer", "Soccer"),
                            ("music", "Music"),
                            ("programming", "Programming"),
                            ("hardware", "Hardware Development"),
                            ("other", "Other"),
                        ],
                        default="basketball",
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("rules", models.TextField(blank=True)),
                ("commitment_level", models.CharField(blank=True, max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("max_teams", models.PositiveIntegerField(default=16)),
                ("team_size_min", models.PositiveIntegerField(default=3)),
                ("team_size_max", models.PositiveIntegerField(default=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leagues",
                        to="groups.group",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leagues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Scrimmage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=280, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("basketball", "Basketball"),
                            ("soccer", "Soccer"),
                            ("music", "Music"),
                            ("programming", "Programming"),
                            ("hardware", "Hardware Development"),
                            ("other", "Other"),
                        ],
                        default="basketball",
                        max_length=32,
                    ),
                ),
                ("location_name", models.CharField(blank=True, max_length=255)),
                ("address", models.CharField(blank=True, max_length=512)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "rrule",
                    models.CharField(
                        blank=True,
                        help_text="Optional iCal RRULE (e.g., FREQ=WEEKLY;BYDAY=SU)",
                        max_length=255,
                    ),
                ),
                ("max_participants", models.PositiveIntegerField(default=10)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="public",
                        max_length=10,
                    ),
                ),
                ("skill_level", models.CharField(blank=True, max_length=64)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("currency", models.CharField(default="USD", max_length=8)),
                ("requires_membership", models.BooleanField(default=False)),
                (
                    "entry_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("auto_pay_enabled", models.BooleanField(default=False)),
                ("team_pay_enabled", models.BooleanField(default=False)),
                (
                    "organizer_fee_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "organizer_fee_flat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "prize_pool_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="published",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrimmages_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scrimmages",
                        to="groups.group",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="LeagueTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("join_code", models.CharField(blank=True, max_length=12)),
                ("wins", models.PositiveIntegerField(default=0)),
                ("losses", models.PositiveIntegerField(default=0)),
                ("draws", models.PositiveIntegerField(default=0)),
                ("points", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="league_teams",
                        to="groups.group",
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="scrimmages.league",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_league_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-points", "name"],
                "unique_together": {("league", "name")},
            },
        ),
        migrations.CreateModel(
            name="PerformanceStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scrimmage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="scrimmages.scrimmage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "scrimmage")},
            },
        ),
        migrations.CreateModel(
            name="ScrimmageParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("player", "Player"),
                            ("coach", "Coach"),
                            ("referee", "Referee"),
                            ("observer", "Observer"),
                        ],
                        default="player",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("confirmed", "Confirmed"),
                            ("declined", "Declined"),
                            ("checked_in", "Checked In"),
                        ],
                        default="confirmed",
                        max_length=16,
                    ),
                ),
                ("rating", models.FloatField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scrimmage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="scrimmages.scrimmage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrimmage_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-joined_at"],
                "unique_together": {("user", "scrimmage")},
            },
        ),
    ]
