# Generated by Django 5.2.7 on 2025-10-27 03:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
        ("leagues", "0001_initial"),
        ("media", "0001_initial"),
        ("scrimmages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="league",
            name="group",
        ),
        migrations.RemoveField(
            model_name="league",
            name="organizer",
        ),
        #migrations.RemoveField(
            #model_name="leagueteam",
            #name="league",
        #),
        migrations.AlterUniqueTogether(
            name="leagueteam",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="leagueteam",
            name="group",
        ),
        migrations.RemoveField(
            model_name="leagueteam",
            name="owner",
        ),
        migrations.AlterUniqueTogether(
            name="scrimmageparticipation",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="scrimmageparticipation",
            name="scrimmage",
        ),
        migrations.RemoveField(
            model_name="scrimmageparticipation",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="scrimmage",
            options={"ordering": ["start_datetime"]},
        ),
        migrations.RenameField(
            model_name="scrimmage",
            old_name="end_time",
            new_name="end_datetime",
        ),
        migrations.RenameField(
            model_name="scrimmage",
            old_name="start_time",
            new_name="start_datetime",
        ),
        migrations.RemoveField(
            model_name="scrimmage",
            name="auto_pay_enabled",
        ),
        migrations.RemoveField(
            model_name="scrimmage",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="scrimmage",
            name="fee_amount",
        ),
        migrations.RemoveField(
            model_name="scrimmage",
            name="is_recurring",
        ),
        migrations.RemoveField(
            model_name="scrimmage",
            name="organizer_fee_flat",
        ),
        migrations.RemoveField(
            model_name="scrimmage",
            name="organizer_fee_percent",
        ),
        migrations.RemoveField(
            model_name="scrimmage",
            name="prize_pool_amount",
        ),
        migrations.RemoveField(
            model_name="scrimmage",
            name="requires_membership",
        ),
        migrations.RemoveField(
            model_name="scrimmage",
            name="rrule",
        ),
        migrations.RemoveField(
            model_name="scrimmage",
            name="skill_level",
        ),
        migrations.RemoveField(
            model_name="scrimmage",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="scrimmage",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="scrimmage",
            name="team_pay_enabled",
        ),
        migrations.AddField(
            model_name="scrimmage",
            name="credit_required",
            field=models.BooleanField(
                default=False,
                help_text="True when creator lacked credits; publish after payment/credit.",
            ),
        ),
        migrations.AddField(
            model_name="scrimmage",
            name="host",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hosted_scrimmages",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scrimmage",
            name="is_paid",
            field=models.BooleanField(
                default=False, help_text="Derived from entry_fee > 0"
            ),
        ),
        migrations.AddField(
            model_name="scrimmage",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scrimmage",
            name="league",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scrimmages",
                to="leagues.league",
            ),
        ),
        migrations.AddField(
            model_name="scrimmage",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scrimmage",
            name="rating_avg",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="scrimmage",
            name="rating_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scrimmage",
            name="teams",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="scrimmage",
            name="waitlist_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="scrimmage",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="scrimmage",
            name="currency",
            field=models.CharField(default="USD", max_length=6),
        ),
        migrations.AlterField(
            model_name="scrimmage",
            name="location_name",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name="scrimmage",
            name="max_participants",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name="scrimmage",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("upcoming", "Upcoming"),
                    ("ongoing", "Ongoing"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="scrimmage",
            name="title",
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name="scrimmage",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("members", "Members"),
                    ("private", "Private"),
                ],
                default="public",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="RecurrenceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                        max_length=20,
                    ),
                ),
                ("interval", models.PositiveIntegerField(default=1)),
                ("day_of_week", models.CharField(blank=True, max_length=9)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "auto_generate",
                    models.BooleanField(
                        default=True,
                        help_text="When processed, create next occurrences automatically.",
                    ),
                ),
                (
                    "suggest_similar",
                    models.BooleanField(
                        default=True, help_text="Suggest this pattern in create forms."
                    ),
                ),
                (
                    "scrimmage",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurrence_rule",
                        to="scrimmages.scrimmage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScrimmageCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrimmage_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="scrimmage",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scrimmages",
                to="scrimmages.scrimmagecategory",
            ),
        ),
        migrations.CreateModel(
            name="ScrimmageMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("approved", models.BooleanField(default=True)),
                ("file_size", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrimmage_links",
                        to="media.media",
                    ),
                ),
                (
                    "scrimmage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="scrimmages.scrimmage",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_scrimmage_media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScrimmageRSVP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("interested", "Interested"),
                            ("pending_payment", "Pending Payment"),
                            ("waitlisted", "Waitlisted"),
                            ("going", "Going"),
                            ("checked_in", "Checked In"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="interested",
                        max_length=20,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("player", "Player"),
                            ("coach", "Coach"),
                            ("referee", "Referee"),
                            ("observer", "Observer"),
                        ],
                        default="player",
                        max_length=16,
                    ),
                ),
                ("team_name", models.CharField(blank=True, max_length=50, null=True)),
                ("score", models.CharField(blank=True, max_length=50, null=True)),
                ("feedback", models.TextField(blank=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scrimmage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rsvps",
                        to="scrimmages.scrimmage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrimmage_rsvps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScrimmageType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("approved", models.BooleanField(default=False)),
                ("custom_field_schema", models.JSONField(blank=True, default=dict)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="types",
                        to="scrimmages.scrimmagecategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrimmage_types",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["category__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="ScrimmageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "base_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Prefill payload for creating scrimmages.",
                    ),
                ),
                (
                    "is_shared",
                    models.BooleanField(
                        default=False, help_text="Visible to others if approved."
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        default=False,
                        help_text="Admin approval required for public use.",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Listed in global template library once approved.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrimmage_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scrimmage_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scrimmages.scrimmagetype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="scrimmage",
            name="scrimmage_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional format/type (e.g., 3v3, hackathon, cookoff).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scrimmages",
                to="scrimmages.scrimmagetype",
            ),
        ),
        migrations.AddIndex(
            model_name="scrimmage",
            index=models.Index(
                fields=["status", "start_datetime"],
                name="scrimmages__status_93221f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scrimmage",
            index=models.Index(
                fields=["visibility", "start_datetime"],
                name="scrimmages__visibil_78b3c8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scrimmage",
            index=models.Index(
                fields=["category", "start_datetime"],
                name="scrimmages__categor_00ba18_idx",
            ),
        ),
        migrations.DeleteModel(
            name="League",
        ),
        migrations.DeleteModel(
            name="LeagueTeam",
        ),
        migrations.DeleteModel(
            name="ScrimmageParticipation",
        ),
        migrations.AddIndex(
            model_name="recurrencerule",
            index=models.Index(
                fields=["active", "frequency", "interval"],
                name="scrimmages__active_46bc1c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scrimmagecategory",
            index=models.Index(
                fields=["approved", "created_at"], name="scrimmages__approve_993062_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="scrimmagecategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("approved", True)),
                fields=("name",),
                name="uniq_public_category_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="scrimmagecategory",
            constraint=models.UniqueConstraint(
                fields=("name", "created_by"), name="uniq_user_category_proposal"
            ),
        ),
        migrations.AddIndex(
            model_name="scrimmagemedia",
            index=models.Index(
                fields=["scrimmage", "approved", "created_at"],
                name="scrimmages__scrimma_fba3fa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scrimmagersvp",
            index=models.Index(
                fields=["scrimmage", "status", "created_at"],
                name="scrimmages__scrimma_65db3e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scrimmagersvp",
            index=models.Index(
                fields=["user", "scrimmage"], name="scrimmages__user_id_1d6a85_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scrimmagersvp",
            unique_together={("scrimmage", "user")},
        ),
        migrations.AddIndex(
            model_name="scrimmagetype",
            index=models.Index(
                fields=["approved", "category"], name="scrimmages__approve_11b1e4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="scrimmagetype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("approved", True)),
                fields=("category", "name"),
                name="uniq_public_type_per_category",
            ),
        ),
        migrations.AddConstraint(
            model_name="scrimmagetype",
            constraint=models.UniqueConstraint(
                fields=("category", "name", "created_by"),
                name="uniq_user_type_proposal",
            ),
        ),
        migrations.AddIndex(
            model_name="scrimmagetemplate",
            index=models.Index(
                fields=["is_shared", "approved", "is_public"],
                name="scrimmages__is_shar_5f927e_idx",
            ),
        ),
    ]
