# Generated by Django 5.2.7 on 2025-10-19 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrimmages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leagueteam",
            name="league",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="scrimmages.league",
            ),
        ),
    ]
