# Generated by Django 5.2.7 on 2025-10-19 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_location_locationeditlog_and_more"),
        ("scrimmages", "0002_alter_leagueteam_league"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrimmageCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="scrimmage",
            name="auto_pay_enabled",
        ),
        migrations.RemoveField(
            model_name="scrimmage",
            name="fee_amount",
        ),
        migrations.RemoveField(
            model_name="scrimmage",
            name="requires_membership",
        ),
        migrations.RemoveField(
            model_name="scrimmage",
            name="skill_level",
        ),
        migrations.AddField(
            model_name="scrimmage",
            name="custom_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="scrimmage",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scrimmages",
                to="organizations.location",
            ),
        ),
        migrations.AlterField(
            model_name="league",
            name="category",
            field=models.CharField(
                choices=[
                    ("basketball", "Basketball"),
                    ("football", "Football"),
                    ("soccer", "Soccer"),
                    ("volleyball", "Volleyball"),
                    ("other", "Other"),
                ],
                default="basketball",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="scrimmage",
            name="category",
            field=models.CharField(
                choices=[
                    ("basketball", "Basketball"),
                    ("football", "Football"),
                    ("soccer", "Soccer"),
                    ("volleyball", "Volleyball"),
                    ("other", "Other"),
                ],
                default="basketball",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="scrimmage",
            name="rrule",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="RecurrenceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                        max_length=20,
                    ),
                ),
                ("interval", models.PositiveIntegerField(default=1)),
                ("day_of_week", models.CharField(blank=True, max_length=9)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "scrimmage",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurrence_rule",
                        to="scrimmages.scrimmage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScrimmageType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=160, unique=True)),
                ("custom_field_schema", models.JSONField(blank=True, default=dict)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="types",
                        to="scrimmages.scrimmagecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["category__name", "name"],
                "unique_together": {("category", "name")},
            },
        ),
        migrations.CreateModel(
            name="ScrimmageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("base_settings", models.JSONField(blank=True, default=dict)),
                ("is_shared", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrimmage_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scrimmage_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scrimmages.scrimmagetype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="scrimmage",
            name="scrimmage_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scrimmages",
                to="scrimmages.scrimmagetype",
            ),
            preserve_default=False,
        ),
    ]
