# Generated by Django 5.2.7 on 2025-11-03 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrimmages", "0002_remove_league_group_remove_league_organizer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrimmagetype",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scrimmage_types",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
