# Generated by Django 5.2.7 on 2025-11-03 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_location_locationeditlog_and_more"),
        ("scrimmages", "0003_alter_scrimmagetype_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scrimmage",
            name="location_name",
        ),
        migrations.AddField(
            model_name="scrimmage",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Select an organization location for this scrimmage.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scrimmages",
                to="organizations.location",
            ),
        ),
    ]
