# Generated by Django 5.2.7 on 2025-11-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrimmages", "0004_remove_scrimmage_location_name_scrimmage_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrimmage",
            name="payment_options",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Available payment methods for this scrimmage.",
            ),
        ),
        migrations.AddField(
            model_name="scrimmagersvp",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("online", "Online"),
                    ("cash", "Cash on Event Day"),
                    ("transfer", "Zelle / Bank Transfer"),
                    ("tentative", "Tentative RSVP"),
                ],
                default="tentative",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="scrimmagersvp",
            name="reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
